- name: Install Control Plane Components
  hosts: control*
  become: true
  vars_files:
    - certificate.yml
    - kubecomponents.yml
  tasks:
    # - name: Download Required Binaries # noqa: run-once[task]
    #   delegate_to: localhost
    #   run_once: true
    #   become: false
    #   ansible.builtin.import_role:
    #     name: install_kube_components
    #     tasks_from: download_binaries.yml

    # - name: Install Etcd
    #   become: true
    #   ansible.builtin.import_role:
    #     name: install_kube_components
    #     tasks_from: install_etcd.yml

    # - name: Install Kube Control Plane Components
    #   become: true
    #   ansible.builtin.import_role:
    #     name: install_kube_components
    #     tasks_from: install_kube_control_components.yml

    # - name: Install Container Runtimes
    #   ansible.builtin.import_role:
    #     name: install_kube_components
    #     tasks_from: install_container_runtime_binaries.yml

    # - name: Install Kubelet
    #   ansible.builtin.import_role:
    #     name: install_kube_components
    #     tasks_from: install_kubelet.yml

    - name: Install Kube-Proxy
      ansible.builtin.import_role:
        name: install_kube_components
        tasks_from: install_kube_proxy.yml
