---
- name: Download etcd
  block:
    - name: Download etcd Binary
      ansible.builtin.get_url:
        url: "{{ install_kube_components_etcd_download_url }}"
        dest: "{{ install_kube_components_binary_location_host }}"
        mode: "0755"
      register: download_info

    - name: Create Output Directory
      ansible.builtin.file:
        path: "{{ install_kube_components_binary_location_host }}/etcd"
        state: directory
        mode: "0755"

    - name: Untar etcd
      ansible.builtin.unarchive:
        src: "{{ download_info.dest }}"
        dest: "{{ install_kube_components_binary_location_host }}/etcd"
        extra_opts: [--strip-components=1]

- name: Download containerd
  block:
    - name: Download containerd Binary
      ansible.builtin.get_url:
        url: "{{ install_kube_components_containerd_download_url }}"
        dest: "{{ install_kube_components_binary_location_host }}"
        mode: "0755"
      register: download_info

    - name: Create Output Directory
      ansible.builtin.file:
        path: "{{ install_kube_components_binary_location_host }}/containerd"
        state: directory
        mode: "0755"

    - name: Untar containerd
      ansible.builtin.unarchive:
        src: "{{ download_info.dest }}"
        dest: "{{ install_kube_components_binary_location_host }}/containerd"
        extra_opts: [--strip-components=1]

- name: Download crictl
  block:
    - name: Download crictl Binary - "{{ install_kube_components_crictl_download_url }}"
      ansible.builtin.get_url:
        url: "{{ install_kube_components_crictl_download_url }}"
        dest: "{{ install_kube_components_binary_location_host }}"
        mode: "0755"
      register: download_info

    - name: Create Output Directory
      ansible.builtin.file:
        path: "{{ install_kube_components_binary_location_host }}/crictl"
        state: directory
        mode: "0755"

    - name: Untar crictl
      ansible.builtin.unarchive:
        src: "{{ download_info.dest }}"
        dest: "{{ install_kube_components_binary_location_host }}/crictl"

- name: Download cniplugin
  block:
    - name: Download cniplugin Binary
      ansible.builtin.get_url:
        url: "{{ install_kube_components_cni_plugin }}"
        dest: "{{ install_kube_components_binary_location_host }}"
        mode: "0755"
      register: download_info

    - name: Create Output Directory
      ansible.builtin.file:
        path: "{{ install_kube_components_binary_location_host }}/cniplugin"
        state: directory
        mode: "0755"

    - name: Untar cniplugin
      ansible.builtin.unarchive:
        src: "{{ download_info.dest }}"
        dest: "{{ install_kube_components_binary_location_host }}/cniplugin"
        extra_opts: [--strip-components=1]

- name: Download runc
  ansible.builtin.get_url:
    url: "{{ install_kube_components_runc_download_url }}"
    dest: "{{ install_kube_components_binary_location_host }}"
    mode: "0755"
  register: download_info

- name: Download Kubernetes Binary
  ansible.builtin.get_url:
    url: "{{ install_kube_components_kubernetes_download_url }}/{{ item }}"
    dest: "{{ install_kube_components_binary_location_host }}/{{ item }}"
    mode: "0755"
  register: download_info
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubelet
    - kube-proxy
