- name: Install etcd Binary To Control Planes
  ansible.builtin.file:
    src: "{{ install_kube_components_binary_location_guest }}/etcd/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    mode: "0777"
  loop:
    - etcd
    - etcdctl
    - etcdutl

- name: Generate Etcd Unit File
  ansible.builtin.template:
    src: "{{ role_path }}/templates/etcd.service.j2"
    dest: /etc/systemd/system/etcd.service
    mode: '755'

- name: Start etcd Service
  ansible.builtin.systemd_service:
    name: etcd
    daemon_reload: true
    enabled: true
    state: started
  register: output

- name: Ensure Service Status is Running
  ansible.builtin.debug:
    msg: "{{ output.status }}"

- name: Verify etc status
  ansible.builtin.shell:
    cmd: >
      ETCDCTL_API=3 etcdctl member list \
      --endpoints=https://127.0.0.1:2379 \
      --cacert=/var/lib/kubernetes/kube-root-ca.crt \
      --cert=/etc/etcd/kube-apiserver.crt \
      --key=/etc/etcd/kube-apiserver.key
  register: output

- name: Print Etcd Status
  ansible.builtin.debug:
    msg: "{{ output.status }}"
