# - name: Install Kubelet Binary
#   ansible.builtin.file:
#     src: "{{ install_kube_components_binary_location_guest }}/kubelet/kubelet"
#     dest: "/usr/local/bin/kubelet"
#     state: link
#     mode: "0777"
  
- name: Transfer Kubelet Config
  ansible.builtin.template:
    src: "{{ role_path }}/templates/kubelet-config.yml.j2"
    dest: /var/lib/kubelet/kubelet-config.yml
    mode: '0755'

- name: Transfer Kubelet Systemd Unit File
  ansible.builtin.template:
    src: "{{ role_path }}/templates/kubelet.service.j2"
    dest: /etc/systemd/system/kubelet.service
    mode: '0755'

- name: Start Service - Kubelet
  ansible.builtin.systemd_service:
    name: kubelet.service
    daemon_reload: true
    enabled: true
    state: started