- name: Install Kube Control Plane Components
  ansible.builtin.file:
    src: "{{ install_kube_components_binary_location_guest }}/{{ item }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    mode: "0777"
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy
    - kubelet


- name: Create kubernetes etc folder
  ansible.builtin.file:
    path: /etc/kubernetes/config
    state: directory
    mode: '0755'

- name: Transfer Kube Scheduler Config
  ansible.builtin.template:
    src: "{{ role_path }}/templates/kube-scheduler.yml.j2"
    dest: /etc/kubernetes/config/kube-scheduler.yaml
    mode: '755'

- name: Generate Unit File
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: '755'
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: Start Service - {{ item }}
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    daemon_reload: true
    enabled: true
    state: started
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

# - name: Ensure Service Status is Running
#   ansible.builtin.debug:
#     msg: "{{ output.status }}"
