# - name: Install Kube-Proxy Binary
#   ansible.builtin.file:
#     src: "{{ install_kube_components_binary_location_guest }}/kube-proxy/kube-proxy"
#     dest: "/usr/local/bin/kube-proxy"
#     state: link
#     mode: "0777"

- name: Create Kube-Proxy Directory
  ansible.builtin.file:
    path: /var/lib/kube-proxy
    state: directory
    mode: "0755"

- name: Link Kube-Proxy KubeConfig
  ansible.builtin.file:
    src: "{{ install_kube_components_binary_location_guest }}/kube-proxy/kube-proxy.kubeconfig"
    dest: /var/lib/kube-proxy/kube-proxy.kubeconfig
    state: link
    mode: "0775"

- name: Transfer Kube-Proxy Systemd Unit File
  ansible.builtin.template:
    src: "{{ role_path }}/templates/kube-proxy.service.j2"
    dest: /etc/systemd/system/kube-proxy.service
    mode: "0755"

- name: Start Service - Kube-Proxy
  ansible.builtin.systemd_service:
    name: kube-proxy
    daemon_reload: true
    enabled: true
    state: started